export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_SERVICE = "CHANGE_SERVICE";
export const CHANGE_ID_TO_EDIT = "CHANGE_ID_TO_EDIT";
export const CHANGE_FILTER = "CHANGE_FILTER";
